# Use the official Node.js image as a base
FROM node:18.18.0-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install dependencies (for initial container build)
COPY package*.json ./
RUN npm install --production

# Expose the port your app runs on
EXPOSE 8080

# Command to run the application
CMD ["npm", "start"]

